name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: messaging_app_db
          MYSQL_USER: user
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_PASSWORD: password

        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r messaging_app/requirements.txt
          pip install flake8 pytest-cov

      - name: Run flake8 linting
        run: |
          cd messaging_app
          flake8 . --exit-zero --max-line-length=120

      - name: Run tests with coverage
        env:
          DATABASE_URL: mysql://root:root@localhost:3306/messaging_app_db
        run: |
          cd messaging_app
          python -m pytest tests --junitxml=reports/junit-report.xml --cov=. --cov-report=xml:reports/coverage.xml

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: messaging_app/reports/

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: messaging_app/reports/coverage.xml
