apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-green
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app-green
  template:
    metadata:
      labels:
        app: messaging-app-green
    spec:
      containers:
      - name: messaging-app
        image: bunnye/messaging-app:v2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_HOST
          value: "mysql-service"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-password
        - name: DATABASE_NAME
          value: "messaging_db"
